### ISSUE TITLE
This is the unit tests for single thread matrix

### ISSUE THREAD

**Issue by Kaiser-Yang** [Kaiser-Yang/matrix-calculation-accelarator#17]
This comment is to arrange tasks of single thread unit tests.

Task-List (`test/src/single_thread_matrix_calculation_test.cpp`):
@Quentin9922 
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelarator/assets/58209855/75253fcc-e0ce-41b6-96d7-bcff144fc77e)
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelarator/assets/58209855/d34295a0-644a-4dd0-8241-a5e75d15c6cc)

@Liu-shui-chan-yuan 
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelarator/assets/58209855/2d2d8439-38f8-4c09-8543-8c474291eb90)

@propanone1006 
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelarator/assets/58209855/03bc4237-370f-4dd2-bfd5-3a372ecfd716)

@Kaiser-Yang:
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelarator/assets/58209855/c2896718-fab8-40c2-b453-c39637ec362a)

**Comment by Kaiser-Yang** [comment]
@Kaiser-Yang finished. 

See #18.

**Comment by propanone1006** [comment]
这是来自QQ邮箱的自动回复邮件。你好，您的邮件我已收到，我会尽快处理。
